version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongodb
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
      